### PR TITLE
Fix a typo and added missing "else" in the nvs code for "int" type

### PR DESCRIPTION
**Pull request by dashxdr**
I'm not an expert on merging, I want to get _some_ of my changes to merge in because the original tree is wrong, but my tree is kind of customized for my uses.

Specifically these ought to be merged:
filesystem/Bluetooth.js
main/module_nvs.c
main/modules.c

This is just a useful function for viewing js objects:
filesystem/treeify.js

These should NOT be merged:
Makefile
sdkconfig
partitions.csv

### CODE REVIEW

**Comment by nkolban** [comment]
It has conflicts.

**Comment by dashxdr** [comment]
I don't know how to resolve the conflict. My copy of partitions.csv can be abandoned. I wish I could just say, "These X files are part of the pull request". Google search for how to resolve conflicts seems to focus on the owner's side of things (meaning you).

**Comment by dashxdr** [comment]
crap I want to just delete this entire attempt...

**Comment by dashxdr** [comment]
OK this should be good to go. I wanted to create a new branch on my fork but messed it up... thanks for your patience. treeify.js is optional but I included it in the PR. Thanks--

**Pull request merged**
