### PR TITLE
fixes SPIFFS file reading; adds missing partition file

### PR DESCRIPTION
**Pull request by boneskull**
see https://github.com/espressif/esp-idf/issues/1437#issuecomment-354145860

### CODE REVIEW

**Comment by boneskull** [comment]
it was able to read `ide.html` and whatever else:

image

**Comment by dashxdr** [comment]
Still not working for me. I did get the most recent esp-idf and made your sdkconfig tweaks
CONFIG_SPIFFS_META_LENGTH=0
behaviour is the same though.
D (30786) SPIFFS: read: offset:0 rd:128 data spix:0000 is data_pix:0000 addr:00000005

**Comment by dashxdr** [comment]
https://github.com/nkolban/duktape-esp32/issues/24#issuecomment-364710706
I can't see how to link discussions. Anyway it's all fixed, thanks!

**Comment by boneskull** [comment]
# and the issue or PR number (e.g. #24) will link to that issue or PR, if that’s what you mean. glad it’s fixed, sorry I broke it!

**Pull request merged**
