### PR TITLE
Fix readme header format

### PR DESCRIPTION
**Pull request by ryfow**

### CODE REVIEW

**Comment by nkolban** [comment]
Oh sorry ... I missed the pull request.  But my attention is now back on ESP32 Duktape now that I have my hands on some WROVERs.

**Comment by ryfow** [comment]
no worries. I just noticed that the readme was updated.

I think about trying this project out when I get annoyed with micropython but haven't wanted to invest the initial effort of getting it up and running.

**Comment by nkolban** [comment]
I'm always up to practice the installs, builds etc ... if you are interested, I'll be more than happy to work with you as needed.  I'm starting to think that running it with WROVER is probably the way to go.

**Comment by ryfow** [comment]
Are there current build instructions? I tried sorting it out from the docs directory and the Makefile and didn't completely figure it out. I'm getting this when I try:

```shell
$ make
CC extras/module-duktape/duk_module_duktape.o
/home/rfowler/Projects/duktape-esp32/components/duktape/extras/module-duktape/duk_module_duktape.c:5:21: fatal error: duktape.h: No such file or directory
compilation terminated.
/home/rfowler/esp/esp-idf/make/component_wrapper.mk:228: recipe for target 'extras/module-duktape/duk_module_duktape.o' failed
make[1]: *** [extras/module-duktape/duk_module_duktape.o] Error 1
/home/rfowler/esp/esp-idf/make/project.mk:391: recipe for target 'component-duktape-build' failed
make: *** [component-duktape-build] Error 2
```

**Comment by nkolban** [comment]
Checking now

**Comment by nkolban** [comment]
Do you have "duktape" in your "components" folder?

See the following ... https://github.com/nkolban/duktape-esp32/blob/master/docs/Building%20duktape%20from%20github.md

I'll be happy to help live as needed.

**Comment by nkolban** [comment]
Oooh!! Wait ... I see the problem ...

**Comment by nkolban** [comment]
New instructions found here:

https://github.com/nkolban/duktape-esp32/blob/master/docs/Building%20duktape%20from%20github.md

**Pull request closed without merging**
